# Generated by Django 2.1.2 on 2018-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daintree', '0002_category_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
