-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 17:12:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema daintree
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `daintree` ;

-- -----------------------------------------------------
-- Schema daintree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daintree` ;
USE `daintree` ;

-- -----------------------------------------------------
-- Table `daintree`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daintree`.`User` ;

CREATE TABLE IF NOT EXISTS `daintree`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daintree`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daintree`.`Company` ;

CREATE TABLE IF NOT EXISTS `daintree`.`Company` (
  `address` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `nb_employees` INT NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `ethereum_pk` VARCHAR(255) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`User_id`),
  INDEX `fk_Company_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Company_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `daintree`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
